version: "3.7"

services:
  distributed-diffusion:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: dd_app
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/distributed-diffusion:delegated # enable hot code reload in debug mode
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

